# Site settings
title: Abstract Factory Ltd.
email: abstractfactory.io
description: Workflow automation software
version: "2.0.0"
baseurl: ""
url: "http://abstractfactory.io"

collections:
    - chapters
